/**
 * Reads the captured reference stylesheet and emits the design tokens it
 * defines as apps/web/src/styles/moon-tokens.css.
 *
 * The reference ships the Moon design system (open source, MIT —
 * github.com/coingaming/moon-design). We take the token *values* so spacing,
 * radii, elevation and the colour ramps line up exactly; the component CSS
 * itself is not copied.
 *
 *   node scripts/extract-tokens.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHUNKS = join(ROOT, 'asset/bitcasino.io/_next/static/chunks');

const css = readdirSync(CHUNKS)
  .filter((f) => f.endsWith('.css'))
  .map((f) => readFileSync(join(CHUNKS, f), 'utf8'))
  .join('\n');

/** Returns the body of the first rule whose selector list contains `selector`. */
function ruleBody(selector) {
  const at = css.indexOf(selector);
  if (at === -1) throw new Error(`selector ${selector} not found in captured CSS`);
  const open = css.indexOf('{', at);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}' && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`unterminated rule for ${selector}`);
}

/** All `--custom: value` declarations in a rule body, first definition wins. */
function declarations(body) {
  const out = new Map();
  for (const [, name, value] of body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
    if (!out.has(name)) out.set(name, value.trim());
  }
  return out;
}

const theme = declarations(ruleBody('.light-theme'));
const root = declarations(ruleBody(':root'));

// Sort `--color-piccolo-9` after `--color-piccolo-8`, not after `--color-piccolo-12`.
const natural = (a, b) =>
  a.replace(/\d+/g, (n) => n.padStart(4, '0')).localeCompare(b.replace(/\d+/g, (n) => n.padStart(4, '0')));

const section = (title, entries) =>
  entries.length
    ? `\n  /* ${title} */\n` + entries.map(([k, v]) => `  ${k}: ${v};`).join('\n') + '\n'
    : '';

const pick = (map, test) => [...map].filter(([k]) => test(k)).sort(([a], [b]) => natural(a, b));

const isRamp = (k) => /^--color-[a-z]+-(\d+|alpha-\d+|shadow-\d+|black|white)$/.test(k);
const isSemantic = (k) => /^--color-(background|text|icon|border)-/.test(k);
const isContext = (k) => k.startsWith('--context-');
const isComponent = (k) => k.startsWith('--component-');

const out = `/* ---------------------------------------------------------------------------
 * GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
 *
 * Design tokens as the reference site defines them: the Moon design system
 * (MIT, github.com/coingaming/moon-design). Values only — no component CSS.
 *
 * Layer order matters. Ramps are raw colour; the semantic layer names roles in
 * terms of ramps; context and component layers build on the semantic names. A
 * dark theme only needs to redefine the ramps.
 * ------------------------------------------------------------------------- */

:root,
.light-theme {${section('scale', pick(root, (k) => /^--(spacing|radius|border-width|opacity)/.test(k)).concat(pick(theme, (k) => /^--(spacing-space|radius-\d|radius-[is]-)/.test(k))))}${section('elevation', pick(root, (k) => k.startsWith('--shadow-')))}${section('colour ramps', pick(theme, isRamp))}${section('semantic roles', pick(theme, isSemantic))}${section('contextual variants', pick(theme, isContext))}${section('component radii', pick(theme, isComponent))}}
`;

const dest = join(ROOT, 'apps/web/src/styles/moon-tokens.css');
writeFileSync(dest, out);

const count = (test) => [...theme].filter(([k]) => test(k)).length;
console.log(`wrote ${dest.replace(ROOT + '\\', '')}`);
console.log(`  ramps      ${count(isRamp)}`);
console.log(`  semantic   ${count(isSemantic)}`);
console.log(`  context    ${count(isContext)}`);
console.log(`  component  ${count(isComponent)}`);
