/**
 * Downloads the two open-licensed families the reference site uses
 * (DM Sans + Space Grotesk, both SIL Open Font License 1.1) from Google Fonts
 * and self-hosts them as woff2 under apps/web/public/fonts.
 *
 * Self-hosting avoids a third-party request on first paint and keeps the app
 * working offline. Run: npm run fonts:fetch
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT = path.resolve(import.meta.dirname, '../apps/web/public/fonts');

// A modern-browser UA makes the CSS endpoint return woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'DM Sans', query: 'DM+Sans:wght@400;500;700', slug: 'dm-sans' },
  { name: 'Space Grotesk', query: 'Space+Grotesk:wght@300;400;500;700', slug: 'space-grotesk' },
];

async function fetchFamily({ name, query, slug }) {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${query}&display=swap`;
  const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${name}: CSS request failed (${res.status})`);
  let css = await res.text();

  // Keep only the latin subset; the reference site is latin-only.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
    .filter(([, subset]) => subset === 'latin')
    .map(([, , block]) => block);

  const files = [];
  let out = '';
  for (const block of blocks) {
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    if (!url) continue;

    const filename = `${slug}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`;
    const bin = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`${name} ${weight}: download failed (${bin.status})`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(path.join(OUT, filename), buf);
    files.push({ filename, weight, style, bytes: buf.length });

    out +=
      `@font-face {\n` +
      `  font-family: "${name}";\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("/fonts/${filename}") format("woff2");\n` +
      `}\n\n`;
  }
  return { files, css: out };
}

await mkdir(OUT, { recursive: true });

let faceCss =
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n' +
  ' * DM Sans and Space Grotesk are licensed under the SIL Open Font License 1.1.\n' +
  ' * See docs/07-assets.md for licensing notes.\n' +
  ' */\n\n';

for (const family of FAMILIES) {
  const { files, css } = await fetchFamily(family);
  faceCss += css;
  for (const f of files) {
    console.log(`  ${f.filename.padEnd(30)} ${String(f.bytes).padStart(7)} bytes`);
  }
}

await writeFile(path.resolve(import.meta.dirname, '../apps/web/src/styles/fonts.css'), faceCss);
console.log('\nWrote apps/web/src/styles/fonts.css');
