import { Link } from 'react-router-dom';

const CATEGORIES = [
  ['Getting Started', '/help-center'],
  ['Your Account', '/help-center'],
  ['Your Transactions', '/help-center'],
  ['Your rewards', '/help-center'],
  ['Payment Options', '/help-center'],
  ['About Crypto', '/help-center'],
  ['How to buy Crypto', '/help-center'],
  ['Loyalty Club', '/loyalty'],
  ['Bitcasino Information', '/help-center/terms-and-conditions'],
];

const RELATED_ARTICLES = [
  ['How many games are there in Bitcasino?', '/help-center'],
  ['How to buy crypto using P2P on Binance?', '/help-center'],
  ['Registering at Bitcasino', '/register'],
];

const seedRows = [
  ['serverSeed', 'Server', 'Secret random value revealed after the round'],
  ['serverSeedHash', 'Derived', 'SHA256 hash of the Server Seed'],
  ['clientSeed', 'Player', 'Player-provided source of randomness'],
  ['nonce', 'Counter', 'Increments with every random event'],
  ['initialShuffle', 'Server', 'Initial deck or board state, for card games only'],
  ['initialShuffleHash', 'Derived', 'Commitment to the initial deck or board state'],
  ['finalShuffle', 'Server', 'Final deck or board state after the round'],
];

const publishedRows = [
  ['clientSeed', 'Yes', 'Yes'],
  ['serverSeedHash', 'Yes', 'Yes'],
  ['nonce', 'Yes', 'Yes'],
  ['initialShuffleHash', 'Yes', 'Yes'],
  ['serverSeed', 'No', 'Yes'],
  ['initialShuffle', 'No', 'Yes'],
  ['finalShuffle', 'No', 'Yes'],
];

function Breadcrumbs() {
  return (
    <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1 text-sm text-bulma">
      <Link to="/" className="hover:text-piccolo">Bitcasino</Link>
      <span aria-hidden="true">›</span>
      <Link to="/help-center" className="hover:text-piccolo">Help centre</Link>
      <span aria-hidden="true">›</span>
      <Link to="/help-center" className="hover:text-piccolo">Getting Started</Link>
      <span aria-hidden="true">›</span>
      <span>Learn about Bitcasino Originals provably fair games</span>
    </nav>
  );
}

function Categories() {
  return (
    <aside className="hidden min-w-72 self-start md:block md:ps-8 lg:min-w-[280px] lg:ps-4">
      <h2 className="mb-4 text-2xl font-normal leading-8 text-bulma">Categories</h2>
      <div className="divide-y divide-beerus border-t border-beerus">
        {CATEGORIES.map(([label, to]) => (
          <Link key={label} to={to} className="block py-4 text-base text-bulma hover:text-piccolo">{label}</Link>
        ))}
      </div>
    </aside>
  );
}

function DataTable({ headers, rows }) {
  return (
    <div className="my-5 overflow-x-auto rounded-md border border-beerus">
      <table className="min-w-full border-collapse text-left text-sm">
        <thead className="bg-gohan text-bulma">
          <tr>{headers.map((header) => <th key={header} className="whitespace-nowrap border-b border-beerus px-3 py-2 font-bold">{header}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`} className="border-b border-beerus px-3 py-2 last:border-b-0">{cell}</td>)}</tr>)}
        </tbody>
      </table>
    </div>
  );
}

function CodeBlock({ children }) {
  return <pre className="my-5 overflow-x-auto rounded-md bg-gohan p-4 text-sm leading-6 text-bulma"><code>{children}</code></pre>;
}

function Section({ title, children }) {
  return <section><h2 className="mb-4 mt-10 text-xl font-bold leading-7 text-bulma">{title}</h2>{children}</section>;
}

function Article() {
  return (
    <article className="min-w-0 max-w-[800px] text-[15px] leading-6 text-bulma md:text-base md:leading-7">
      <div className="mb-8">
        <p className="mb-2 text-[10px] uppercase leading-4 tracking-[0.5px] text-trunks">Getting Started</p>
        <h1 className="font-primary text-2xl font-bold leading-8 text-bulma">Learn about Bitcasino Originals provably fair games</h1>
      </div>

      <Section title="What is Provably Fair?">
        <p>Provably fair is an approach used in online gaming that allows every result to be independently verified as genuinely random.</p>
        <p className="mt-4">It provides a cryptographic guarantee that game outcomes cannot be altered after a bet is placed. By combining player-provided data, server-generated data and publicly verifiable cryptographic commitments, anyone can independently reproduce and verify the outcome of a round.</p>
        <p className="mt-4">This ensures that every result remains unpredictable before the round and verifiable after it has completed.</p>
      </Section>

      <Section title="How We Keep Our Original Games Provably Fair">
        <p>Every outcome is generated using three components:</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Server Seed</h3>
        <p>A secret random value generated by the server. Before gameplay begins, the server publishes a cryptographic hash of the Server Seed. This proves the Server Seed existed before the round started without revealing its value. After the round resolves, the Server Seed is revealed and can be verified against the previously published hash.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Client Seed</h3>
        <p>A value contributed by the player. Players may choose their own Client Seed or use a system-generated value. It becomes part of the randomness generation process and can be changed at any time.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Nonce</h3>
        <p>A counter that increases with every random event. The Nonce ensures that each random result remains unique, even when the same Server Seed and Client Seed are used.</p>
      </Section>

      <Section title="Provably Fair - Verification Guide">
        <p>This guide explains how the provably fair system generates randomness and how you can independently verify the outcome of any round.</p>
        <p className="mt-4">The system operates using a simple principle:</p>
        <p className="mt-4 font-bold">Commit - Play - Reveal</p>
        <p className="mt-4">The server first commits to a Server Seed by publishing its hash. Gameplay then takes place using the Server Seed, Client Seed and Nonce. Once the round has completed, the Server Seed is revealed so that the entire process can be independently verified.</p>
      </Section>

      <Section title="Table of Contents">
        <ul className="list-disc space-y-1 ps-7 marker:text-piccolo md:ps-8">
          {['Trust Model', 'Seeds, Hashes and Nonces', 'Randomness Generation', 'RNG Translation', 'Shuffling', 'Deck Commitment', 'Outcome Mapping', 'How to Verify a Result', 'Reference Verifier', 'Worked Example', 'Notes'].map((item) => <li key={item}>{item}</li>)}
        </ul>
      </Section>

      <Section title="Trust Model">
        <p>Before a round begins, the server generates a secret Server Seed and publishes:</p>
        <CodeBlock>{'serverSeedHash = SHA256(serverSeed)'}</CodeBlock>
        <p>Because cryptographic hashes are one-way functions, the Server Seed remains hidden while the commitment remains publicly visible. After the round resolves, the Server Seed is revealed. Players can then verify:</p>
        <CodeBlock>{'SHA256(serverSeed) == serverSeedHash'}</CodeBlock>
        <p>If the values match, the Server Seed could not have been modified after the commitment was made.</p>
      </Section>

      <Section title="Seeds, Hashes and Nonces">
        <DataTable headers={['Value', 'Origin', 'Meaning']} rows={seedRows} />
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">What Is Published When</h3>
        <DataTable headers={['Value', 'Before / During Round', 'After Round Resolves']} rows={publishedRows} />
      </Section>

      <Section title="Randomness Generation">
        <p>Every random value is generated from the combination of Server Seed, Client Seed and Nonce. The inputs are combined using HMAC-SHA256 to produce a deterministic cryptographic value.</p>
        <CodeBlock>{'Server Seed + Client Seed + Nonce\n            |\n        HMAC-SHA256\n            |\n     Cryptographic Value'}</CodeBlock>
        <p>This value is then used to initialize a ChaCha20-based random number generator. ChaCha20 is designed to generate secure and statistically uniform random values.</p>
        <p className="mt-4">Because the process is deterministic, the same inputs always produce the same output. This allows every outcome to be independently reproduced and verified after the Server Seed has been revealed.</p>
      </Section>

      <Section title="RNG Translation">
        <p>The random values produced by the generator are converted into the numerical ranges required by each game.</p>
        <ul className="mt-4 list-disc space-y-2 ps-7 marker:text-piccolo md:ps-8">
          <li>Dice converts a random value into a roll within the configured range.</li>
          <li>Roulette converts a random value into a wheel position.</li>
          <li>Plinko converts a random value into a landing position.</li>
          <li>Card games use random values to generate deck shuffles.</li>
        </ul>
        <p className="mt-4">Where a game requires a random value within a specific range, rejection sampling ensures every possible outcome remains equally likely and no statistical bias is introduced.</p>
      </Section>

      <Section title="Shuffling">
        <p>Card and board games use the Fisher-Yates shuffle algorithm, a mathematically proven method for generating unbiased random permutations.</p>
        <CodeBlock>{'Ordered Deck\n      |\n Fisher-Yates Shuffle\n      |\n Randomized Deck'}</CodeBlock>
        <p>The shuffle is generated from the same Server Seed, Client Seed and Nonce values used throughout the provably fair system. Because the shuffle is deterministic, any player can reproduce the exact deck order once the Server Seed has been revealed.</p>
      </Section>

      <Section title="Deck Commitment">
        <p>For card games, the initial deck order is committed before any cards are dealt.</p>
        <CodeBlock>{'initialShuffleHash = SHA256(initialShuffle + serverSeed)'}</CodeBlock>
        <p>The hash is published before gameplay begins, while the deck remains hidden. After the round resolves, the initial deck order is revealed and can be verified against the previously published commitment. This ensures the deck could not have been modified after the commitment was made.</p>
      </Section>

      <Section title="Outcome Mapping">
        <p>Each game maps generated random values to a specific result.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Dice</h3><p>A random value is converted into a roll within the game's configured range.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Roulette</h3><p>A random value is converted into a wheel position.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Plinko</h3><p>A random value determines the final landing position and resulting multiplier.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Card Games</h3><p>For Blackjack, Baccarat and Hi-Lo, an ordered deck is shuffled using Fisher-Yates and cards are dealt according to the game rules. Players can independently reproduce the shuffle and verify the resulting card sequence.</p>
      </Section>

      <Section title="How to Verify a Result">
        <p>For a completed round, verification consists of three steps.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Step 1 - Verify the Server Seed</h3>
        <p>Confirm that the revealed Server Seed matches the previously published Server Seed Hash:</p>
        <CodeBlock>{'SHA256(serverSeed) == serverSeedHash'}</CodeBlock>
        <p>This proves that the Server Seed was committed before gameplay began.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Step 2 - Reproduce the Outcome</h3>
        <p>Using the revealed Server Seed, Client Seed and Nonce, reproduce the random values generated during the round. The reproduced values should match the published game result exactly.</p>
        <h3 className="mb-2 mt-7 text-lg font-bold text-bulma">Step 3 - Verify the Deck Commitment</h3>
        <p>For card games, verify:</p>
        <CodeBlock>{'SHA256(initialShuffle + serverSeed) == initialShuffleHash'}</CodeBlock>
        <p>This confirms that the starting deck was committed before gameplay began and was not modified afterwards.</p>
      </Section>

      <Section title="Reference Verifier">
        <p>A reference verifier is provided to allow players to independently reproduce and verify game outcomes. The verifier uses the published Server Seed, Client Seed and Nonce values to recreate the random values generated during gameplay. If the reproduced values match the published results, the round has been verified successfully.</p>
      </Section>

      <Section title="Worked Example">
        <p>Example values:</p>
        <CodeBlock>{'serverSeed =\n3e8f1c0b7a96d5e4f2c1b0a9d8e7f6c5b4a3928170615243f9e8d7c6b5a40312\n\nclientSeed =\nplayer-client-seed-001\n\nserverSeedHash =\nb1198418007c4216afd19221dc11274595663fc55219aaf85b6291e2d5bdebee'}</CodeBlock>
        <p>Verification:</p>
        <CodeBlock>{'SHA256(serverSeed)\n=\nb1198418007c4216afd19221dc11274595663fc55219aaf85b6291e2d5bdebee'}</CodeBlock>
        <p>Since the values match, the Server Seed was correctly committed before gameplay began. Using the same Server Seed, Client Seed and Nonce in the reference verifier will always reproduce the same outcome.</p>
      </Section>

      <Section title="Notes">
        <ul className="list-disc space-y-2 ps-7 marker:text-piccolo md:ps-8">
          <li>Server Seed, Client Seed and Nonce fully determine every outcome.</li>
          <li>The same inputs always generate the same result.</li>
          <li>HMAC-SHA256 derives cryptographic randomness from the seed values.</li>
          <li>ChaCha20 is used as the deterministic random number generator.</li>
          <li>Fisher-Yates is used for deck shuffling in card games.</li>
          <li>Rejection sampling maintains uniform distributions where necessary.</li>
          <li>Any modification to the Server Seed after commitment invalidates the published hash and is immediately detectable.</li>
          <li>Every result can be independently reproduced and verified after the Server Seed has been revealed.</li>
        </ul>
      </Section>
    </article>
  );
}

export function ProvablyFair() {
  return (
    <div className="w-full max-w-[99rem] overflow-x-clip md:mx-auto">
      <Breadcrumbs />
      <div className="mt-8 grid gap-10 md:grid-cols-[minmax(0,1fr)_280px] md:gap-8 lg:grid-cols-[minmax(0,800px)_280px] lg:justify-between">
        <Article />
        <Categories />
      </div>
      <section className="mt-14 border-t border-beerus pt-8">
        <h2 className="mb-5 text-2xl font-bold text-bulma">Related articles</h2>
        <div className="grid gap-6 md:grid-cols-3">
          {RELATED_ARTICLES.map(([label, to]) => (
            <Link key={label} to={to} className="text-xl text-bulma hover:text-piccolo">
              <span className="mb-1 block text-[10px] uppercase leading-4 tracking-[0.5px] text-trunks">Getting Started</span>
              {label}
            </Link>
          ))}
        </div>
      </section>
      <section className="mt-10 max-w-[596px] border-t border-beerus pt-8">
        <h2 className="text-2xl font-bold text-bulma">Other ways to get help</h2>
        <a href="mailto:hello@bitcasino.io" className="mt-4 flex items-center gap-4 bg-gohan px-6 py-4 text-bulma hover:bg-beerus">
          <span aria-hidden="true" className="text-4xl leading-none">@</span>
          <span><strong className="block text-xl">Email us</strong><span className="text-sm text-trunks">hello@bitcasino.io</span></span>
        </a>
      </section>
    </div>
  );
}